### ISSUE TITLE
[dep] Remove vendor folder

### ISSUE THREAD

**Issue by at15** [dyweb/dy-bot#3]
Since we are already using dep, I prefer not committing vendor into repo. Just add `dep ensure` to Makefile and let developer call it.

**Comment by at15** [comment]
@gaocegege I am fixing usage of gommon/log now, I can do this in the same PR

**Comment by at15** [comment]
@gaocegege CI/CD 变慢我倒是没想过(可能已经习惯等 travis 的时候看 b 站了 ...

**Comment by gaocegege** [comment]
我建议你直接在 master 上操作，reset 掉有 vendor 的提交，不然 repo 还是会很大

**Comment by at15** [comment]
@gaocegege reset 可能还是会有记录吧? 我得强改历史记录 push -f 了感觉 ... https://stackoverflow.com/questions/10067848/remove-folder-and-its-contents-from-git-githubs-history

**Comment by gaocegege** [comment]
那肯定得 push -f

**Comment by at15** [comment]
updated using 

````
git filter-branch --tree-filter 'rm -rf vendor' --prune-empty HEAD
`````

the so answer has `git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d
` I didn't use it and things seems to be working ....

**Comment by at15** [comment]
Travis finished in 2 minutes https://travis-ci.org/dyweb/dy-bot/jobs/376691278
